version: '3.8'

services:
  frontend:
    image: story-time-frontend  # Use the image name if you've built and pushed it to a registry
    build: ./frontend/Dockerfile  # Or use this to build the image from a Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 of the container to port 3000 on the host
    depends_on:
      - backend  # This ensures the backend starts first
    # networks:
    #   - app-network

  backend:
    image: story-time-backend  # Use the image name if you've built and pushed it to a registry
    build: .backend/Dockerfile  # Or use this to build the image from a Dockerfile
    volumes:
      - ~/.aws:/root/.aws:ro
    ports:
      - "5000:5000"  # Map port 5000 of the container to port 5000 on the host
    # networks:
    #   - app-network
    environment:
      - DATABASE_URL=your-database-connection-string  # Example environment variable

# networks:
#   app-network:  # Defines a network for your services to communicate
